export const colorOptions = [
  { name: "Grey", color: "#858585" },
  { name: "Purple", color: "#7F2FEF" },
  { name: "Plum", color: "#7E33A2" },
  { name: "Blue", color: "#1556A2" },
  { name: "Colbalt", color: "#2F59EF" },
  { name: "Turquoise", color: "#35D2E9" },
  { name: "Teal", color: "#569FA9" },
  { name: "Green", color: "#0FA852" },
  { name: "Fern", color: "#5B945A" },
  { name: "Yellow", color: "#FFED1F" },
  { name: "Corn", color: "#EBBA3A" },
  { name: "Orange", color: "#FFAF1F" },
  { name: "Brick", color: "#BA4E36" },
  { name: "Rust", color: "#CA661E" },
  { name: "Red", color: "#B80D00" },
  { name: "Magenta", color: "#D233EC" },
  { name: "Pink", color: "#F91A9F" },
]