export const colorOptions = [
  { name: "grey", color: "#858585" },
  { name: "purple", color: "#7F2FEF" },
  { name: "plum", color: "#7E33A2" },
  { name: "blue", color: "#1556A2" },
  { name: "colbalt", color: "#2F59EF" },
  { name: "turquoise", color: "#35D2E9" },
  { name: "teal", color: "#569FA9" },
  { name: "green", color: "#0FA852" },
  { name: "fern", color: "#5B945A" },
  { name: "yellow", color: "#FFED1F" },
  { name: "corn", color: "#EBBA3A" },
  { name: "orange", color: "#FFAF1F" },
  { name: "brick", color: "#BA4E36" },
  { name: "rust", color: "#CA661E" },
  { name: "red", color: "#B80D00" },
  { name: "magenta", color: "#EB00B8" },
  { name: "pink", color: "#F00793" },
]